version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  mongo:
    image: mongo
    networks:
      - internal
  traefik:
    image: traefik:1.7.2-alpine
    ports:
      - 80:80
    volumes:
      - ./traefix.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.frontend.rule=Host:monitor.HOST
      - traefik.port=8080
    networks:
      - web
  multiverse:
    image: xdarkzlightz/multiverse
    depends_on:
      - mongo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - PROJECT_HOST=HOST
      - NETWORK=web
      - SECRET=SECRET
      - BACKEND=BACKEND
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=multiverse
      - PASSWORD=password
    labels:
      - traefik.client.backend=multiverse_client
      - traefik.client.frontend.rule=Host:HOST
      - traefik.client.docker.network=web
      - traefik.client.port=3000
      - traefik.api.backend=multiverse_api
      - traefik.api.frontend.rule=Host:HOST;PathPrefix:/api/
      - traefik.api.docker.network=web
      - traefik.api.port=8080
    networks:
      - web
      - internal
